- src/views/pages/partials/product/card.twig
Related To: https://github.com/SallaApp/Dashboard/pull/7591
> 🐞 Avoid showing countdown for unlimited quantity product

- src/views/pages/product/single.twig
> add product sku  in product page detail 

- src/views/components/product/options/single-option.twig
Reverts SallaApp/theme-raed#93
> Revert "fix option placeholder of single product"

- src/views/layouts/master.twig
> :sparkles: Remove Deplicted Compnent

- src/views/pages/product/index.twig
> 🛠 Hide Sorting List When There Are No Products

- src/views/pages/customer/orders/single.twig
> fix shipping company name

- src/views/components/product/offer.twig
> 🐞 Make The Priority For The Offers To Discounts Tables

- src/views/components/home/enhanced-slider.twig
- src/views/components/home/testimonials.twig
* 
* 
* 
* 
* ![Screenshot 2022-11-17 at 4 31 54 PM](https://user-images.githubusercontent.com/32875906/202474445-f49e2f24-6ca1-409a-bbcd-9ee6df50d175.png)
> 🐞 Testimonials Slider

- src/assets/styles/01-settings/global.scss
- src/assets/styles/02-generic/_mixins.scss
- src/assets/styles/04-components/virtooal.scss
- src/assets/styles/app.scss
* bugfix
* https://app.clickup.com/t/3q2zbh4
* 
* no
*
> 🐞 Virtooal app styles

- src/views/pages/cart.twig
> ✨ Price Quotation

- src/views/pages/thank-you.twig
> fix bug in showing digital codes in page thankyou

- src/views/pages/product/single.twig
* bugfix
* https://app.clickup.com/t/3cjbkbv
* 
* no
*
> fix product description list styles

- src/assets/styles/02-generic/ltr.scss
- src/assets/styles/04-components/menus.scss
> 🐞 LTR arrow icon, menu items icon

- src/views/pages/customer/profile.twig
- src/views/pages/partials/product/options.twig
> Minor enhance for `salla-file-upload`

- src/views/components/home/slider-products-with-header.twig
- twilight.json
* enh
* https://app.clickup.com/t/32ch1vj
* 
* 
*
> ✨ Support Hide/Show Display All Button in `slider-products-with-header` 

- src/views/components/header/advertisement.twig
> :lipstick: center text in ad notification

- src/views/pages/customer/orders/single.twig
> 🖨 show button print

- src/views/pages/customer/orders/index.twig
> show gift icon when order source = buy as gift

- src/views/layouts/customer.twig
> 🐛 fix showing gift icon in order details when order => buy as gift

- src/views/pages/product/single.twig
> 🐞 Listen To Thumbnail Option Change To Auto Slide

- src/assets/styles/04-components/product.scss
* bugfix
* https://sallaops.youtrack.cloud/issue/STORE-16
* 
* no
*
> fix equal height products

- src/assets/js/cart.js
* Bug
* https://www.loom.com/share/528c61cbd6a943ecae277efae607245d
* 
* 
*
> :bug:  fix show offer name on free product

- src/views/pages/product/single.twig
> ✨ buy gift widget subtitle

- src/assets/styles/02-generic/common.scss
- src/assets/styles/04-components/header.scss
- src/assets/styles/04-components/loyalty.scss
- src/views/components/footer/footer.twig
- src/views/components/home/brands.twig
> 🐞 Bugs Fix

- src/views/pages/product/single.twig
> fix gifting system title

- src/views/components/product/offer.twig
> Fix offers price trans

- src/views/pages/thank-you.twig
> add order instructions

- src/views/components/home/fixed-products.twig
- src/views/pages/partials/product/slider.twig
> Consider Prod Limit In Store Blocks

- src/views/pages/product/single.twig
> fix-themes-show-tags-setting

- src/views/components/home/products-slider.twig
- src/views/pages/partials/product/slider.twig
> enable autoplay products slider

- src/assets/js/cart.js
- src/views/pages/cart.twig
> fix quantity update

- src/views/components/home/featured-products-style2.twig
> Support fixed vertical products

- src/views/pages/product/single.twig
> fix: social share button is hidden on mobile view

- twilight.json
* https://github.com/SallaApp/Store/pull/4353
* 
* 
* 
*
> Move more_button To Theme Settings

- src/views/pages/product/single.twig
Task link:
[STORE-862](https://sallaops.youtrack.cloud/issue/STORE-862) يظهر بجانب السعر نقطه
> 🐞 Delete symbol on product page

- src/assets/js/app.js
* bugfix 
* certificate not showing up when clicking on certificate icon on the footer.
* certificate shows up without any issues.
* no
* 
[STORE-960](https://sallaops.youtrack.cloud/issue/STORE-960/aadm-aaml-zr-othyka-alaaamal)
By @Ahmed-S-Abduallah
> 🐛  Fix certificate issue

- src/views/pages/customer/orders/single.twig
> :bug: Delete duplicate quantity and price

- src/views/pages/partials/single-comment.twig
Task link:
[STORE-1258](https://sallaops.youtrack.cloud/issue/STORE-1258) اسم العميل تقييم المنتج - رائد
> 🐞 Comment name

- src/assets/js/partials/product-card.js
- src/assets/styles/02-generic/common.scss
- src/views/components/home/parallax-background.twig
- src/views/layouts/master.twig
> Fixes collections 1

- twilight.json
> ✨ Add Filters As Feature In twilight.json

- src/views/components/home/fixed-products.twig
> fix(themes): Display all button fix

- src/views/components/home/slider-products-with-header.twig
> products with bg block - Display latest products if has no selected

- src/views/pages/product/index.twig
* Bug fix
* Filters showing on search page
* show filters on search page
* No
*
> fix(themes): 🐞 Show Filters On Search Page

- src/views/components/home/fixed-products.twig
This reverts commit b757611fe22655c5f881067de48ac5dc64541a3d.
* 
* 
* 
* 
*
> fix(themes): Display all button fix (#281)

- src/views/pages/cart.twig
- src/views/pages/product/single.twig
* Feature
* No salla-offer twilight component
* We use new salla-offer component
* No
*
> feat(themes): support new component salla-offer

- README.md
* docs update
* old link to Stoplight
* link updated to API Dog
* no
*
> feat(themes): Documentation Link Updated

- CHANGELOG.md
* Docs updated to meet standards 
* N/A
* N/A
* No
* N/A
> feat(themes): ChangeLog README updated

- CHANGELOG.md
* Better looking ChangeLog
* N/A
* N/A
* No
*
> ✨ Detailed Description & Visual Icons Added

- CHANGELOG.md
> feat(themes): 💭Two New Updates Released 💭

- src/views/components/home/testimonials.twig
* BugFix
* The settings for the reviews not passed to the component
* Pass the settings to `salla-reviews` component
* No
*
> fix(themes): support `limit`, `sort` and `without_customer` in salla-reviews

- src/views/components/home/testimonials.twig
* Chore
* unclear name
* using better name for showing customer-info
* No
*
> fix(themes): 🐞 rename `without-customer` => `hide-customer-info`

- src/views/pages/customer/wishlist.twig
> fix(themes): Typo

- CHANGELOG.md
> feat(themes): Theme Raed Changelog Updated

- src/views/components/home/fixed-products.twig
- src/views/components/home/products-slider.twig
Reverts SallaApp/theme-raed#309
> Revert "feat(themes): ✨ Support Using `source`, `source_value` in home components"

- CHANGELOG.md
> feat(themes): Bulk ChangeLog Updates

- package.json
> feat(catalog): Advanced code management

- src/views/layouts/customer.twig
- src/views/pages/customer/orders/single.twig
* Feature
* Shipment tracking is on different external services
* Support new internal service to track order shipments
* No
*
> fix(themes): ✨ Finalize remaining points for Shipment Tracking feature

- src/views/layouts/customer.twig
- src/views/pages/customer/orders/single.twig
> feat(themes): TWILIGHT-1516 add shipment track link

- CHANGELOG.md
* Adding previous July10th ChangeLog data
* N/A
* N/A
* No
*
> feat(themes): ChangeLog July 10th Update

- CHANGELOG.md
> feat(themes): ChangeLog July 10th Update typo fixed

- CHANGELOG.md
> feat(themes): Unify Release Date Formats

- src/views/layouts/master.twig
- src/views/pages/partials/loading-screen-assets.twig
* Chore
* 
* Organize the code, to be more readable
* 
*
> feat(themes): Separate loading screen assets in a standalone twig file

- CHANGELOG.md
> feat(themes): Updating ChangeLog with the Latest Updates

- CHANGELOG.md
> feat(themes): ChangeLog Advertisement Component

- twilight.json
* feature
* using old images
* using new images 
* no
*
> feat(themes): update preview images 

- .github/CODEOWNERS
> feat(themes): Create CODEOWNERS

- CHANGELOG.md
> feat(themes): Latest Release | 17-12-2024

- twilight.json
> feat(themes): Support is_default prop for homepage components + default data for some components

- CHANGELOG.md
* ChangeLog
* N/A
* N/A
* No
*
> Update CHANGELOG.md | 29th December

- twilight.json
> feat(themes): Enhance default data and images

- src/views/pages/blog/single.twig
> hotfix(ui): Blog content wrapping fix

- src/views/pages/product/single.twig
> hotfix(themes): Feature/td 2512 product details fix

- CHANGELOG.md
> feat(themes): New SAR symbol

- src/views/pages/cart.twig
* https://sallaops.youtrack.cloud/issue/SP-5866
* https://sallaops.youtrack.cloud/issue/SP-5866
* 
* 
*
> fix(checkout): Remove without tax label from cart with plus stores 

- CHANGELOG.md
> feat(themes): Update CHANGELOG.md

- src/views/components/home/custom-testimonials.twig
- twilight.json
* Feature
* https://salla-dev.atlassian.net/browse/TD-5383
* 
* no
*
> feat(themes): Add custom testimonials home component

- src/views/pages/customer/profile.twig
> fix(themes): Show custom fields in user profile

- twilight.json
* feature
* Images were previously shown in a small size, which was not ideal for users
* Images are now displayed in a larger size to enhance appearance and usability
* No, this PR does not introduce a breaking change
*
> fix(themes): upload preview image for section "enhanced-slider"

- package.json
- src/views/pages/cart.twig
> feat(themes): support component salla-offer

- CHANGELOG.md
> feat(themes): ChangeLog Updated

- twilight.json
> feat(themes): Enhanced slider note in options, preview images enhance for inside blocks

- CHANGELOG.md
> feat(themes): May 25th ChangeLog Updated

- twilight.json
> feat(ui): Enhance default content for customize-testimonials block

- CHANGELOG.md
> feat(themes): 3 ChangeLogs updated

- src/views/pages/cart.twig
- src/views/pages/customer/orders/single.twig
- src/views/pages/product/single.twig
- src/views/pages/thank-you.twig
* Enhancement
* avoid issue coming from JS when handling big integers
* use ids as string
* 
*
> fix(themes): 🐞 Cast ids as String

- CHANGELOG.md
> feat(themes): Cast Cart Integer

- src/views/pages/product/single.twig
> fix(catalog): remove raw filter from pre order

- src/assets/styles/03-elements/form.scss
* Fix zoom issue when focus on input on mobile.
* 
* 
* 
*
> feat(ui): prevent mobile zoom when inputs receive focus

- src/views/pages/customer/profile.twig
fix custom fields form submission
* 
* 
* 
* 
*
> fix(STD-9403): change profile page to twig
